disallowed-types = [
    # { path = "usize", reason = "variable size" }, # cannot on now, because mocks use it and serde, even if there is no usize in type
    { path = "f64", resdason = "harware dependant" },
    { path = "f32", reason = "harware dependant" },
    { path = "num_traits::float::*", reason = "harware dependant" },
]

disallowed-methods = [
    "std::time::Duration::as_secs_f64",
]
